format_version: 9
pipelines:
  jenkins_credentials_upload:
  group: jenkins_credentials_upload
  label_template: ${jenkins_credentials_upload[:7]}-${COUNT}
  lock_behavior: none
  display_order: 10
  materials:
    edx-platform-yonkers-juniper-release:
      git: https://github.com/edx/configuration.git
      blacklist:
      - '**/*'
      shallow_clone: false
      auto_update: true
      branch: yonkers-juniper
      destination: configuration
      tasks:
      - exec:
          arguments:
          - virtualenv --python /usr/bin/python3.7 config-venv
          command: /bin/bash
          working_directory: configuration
          run_if: passed