format_version: 10
pipelines:
  jenkins_credentials_upload:
    group: jenkins_credentials_upload
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      edx-platform-yonkers-juniper-release:
        git: https://github.com/edx/configuration.git
        shallow_clone: false
        auto_update: true
        branch: yonkers-juniper
        destination: configuration
      ansible-jenkins-creds-api:
        git: git@github.com:Muhammad-Irfan324/ansible-jenkins-creds-api.git
        shallow_clone: false
        auto_update: true
        branch: master
        destination: ansible-jenkins-creds-api
    environment_variables:
        JENKINS_USERNAME: "{{SECRET:[gocd-secret][USERNAME]}}"
        JENKINS_PASSWORD: "{{SECRET:[gocd-secret][PASSWORD]}}"
        AWS_ACCESS: "{{SECRET:[gocd-secret][ACCESS]}}"
        AWS_SECRET_KEY: "{{SECRET:[gocd-secret][SECRET]}}"
        JOB_DIR: "{{SECRET:[gocd-secret][DIRECTORY]}}"
    stages:
    - installing_requirements:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          virtual_env_&_Upload_creds:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - --python
                - /usr/bin/python3.6
                - config-venv
                command: virtualenv
                working_directory: configuration
                run_if: passed
            # - exec:
            #     arguments:
            #     - -c
            #     - source config-venv/bin/activate
            #     command: /bin/bash
            #     working_directory: configuration
            #     run_if: passed                
            - exec:
                arguments:
                - -c
                - sed -i 's/mysqlclient==1.3.0/mysqlclient==1.4.2/g' requirements.txt
                command: /bin/bash
                working_directory: configuration
                run_if: passed
            - exec:
                arguments:
                - -c
                - source config-venv/bin/activate && pip install -r requirements.txt && ansible --version 
                command: /bin/bash
                working_directory: configuration
                run_if: passed         
            - exec:
                arguments:
                - -c
                - source ../configuration/config-venv/bin/activate && ansible-playbook -c local -i "localhost," -e @credentials.yaml create_jenkins_credentials.yml -vvv 
                command: /bin/bash
                working_directory: ansible-jenkins-creds-api
                run_if: passed                